# Generated by Django 3.0.1 on 2020-07-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='uid',
        ),
    ]
